In [15]:
import pandas as pd
import requests
from urllib.request import urlopen
import scraping as s

In [ ]:
df

In [2]:
FFFINAL = 'https://barttorvik.com/2024_fffinal.csv'

In [6]:
df = pd.read_csv(urlopen(FFFINAL))

In [8]:
df = df.reset_index()
df

,level_0,level_1,level_2,level_3,TeamName,eFG%,Rk,eFG% Def,Rk.1,FTR,...,ft%D,rk.5,3P rate,rk.6,3P rate D,rk.7,arate,rk.8,arateD,rk.9
0,North Dakota,50.2,208,52.4,281,32.2,190,29.6,108,30.7,...,33.9,60,43.5,328,40.1,6,7.5,269,5.8,1
1,Appalachian St.,52.7,71,45.4,6,31.6,216,20.7,2,29.4,...,32.6,40,48.6,220,40.7,8,14.6,11,5.9,2
2,San Francisco,55.0,21,49.5,113,23.5,356,37.9,298,29.1,...,37.8,205,54.9,74,49.2,137,10.3,112,5.9,3
3,Bradley,55.1,19,47.6,40,27.5,319,35.1,253,28.1,...,38.3,219,48.6,223,49.5,145,11.7,55,6.0,4
4,Eastern Kentucky,50.6,178,49.8,138,32.0,197,29.5,102,33.1,...,33.4,52,47.1,256,48.3,115,14.2,13,6.2,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
357,Villanova,50.6,175,48.3,63,26.8,333,26.0,29,24.9,...,45.3,355,52.9,115,57.2,325,7.7,263,13.3,358
358,South Carolina,50.9,158,48.4,70,31.8,209,31.6,148,32.8,...,31.3,24,60.5,16,47.6,100,8.2,225,13.5,359
359,William & Mary,48.3,272,52.2,275,31.9,206,34.9,248,27.4,...,36.5,143,50.4,177,46.2,61,4.8,352,13.6,360
360,Stonehill,46.7,322,52.7,297,22.6,358,29.4,97,22.5,...,46.2,359,51.7,140,60.8,358,7.2,287,13.9,361
361,Green Bay,52.4,82,49.4,111,29.4,269,34.2,227,27.3,...,35.3,101,52.1,134,50.8,186,5.9,340,14.8,362

In [9]:
df.columns = ["TEAM","EFG_O","Rk","EFG_D","Rk","FTR","Rk","FTRD","Rk","ORB","Rk","DRB",
                "Rk","TOR","Rk","TORD","Rk","3P_O","rk","3P_D","rk","2P_O","rk","2P_D","rk",
                "ft%","rk","ft%D","rk","3P rate","rk","3P rate D","rk","arate","rk","arateD","rk",
                "1", "2", "3" , "4"]

In [11]:
cols_to_keep = ["TEAM","EFG_O","EFG_D","FTR","FTRD","ORB","DRB","TOR","TORD","3P_O","3P_D","2P_O","2P_D"]

df[cols_to_keep].set_index("TEAM")

,EFG_O,EFG_D,FTR,FTRD,ORB,DRB,TOR,TORD,3P_O,3P_D,2P_O,2P_D
TEAM,,,,,,,,,,,,
North Dakota,50.2,52.4,32.2,29.6,30.7,26.1,15.0,15.3,32.3,35.2,51.5,52.2
Appalachian St.,52.7,45.4,31.6,20.7,29.4,27.8,15.2,14.5,33.2,32.1,53.9,44.0
San Francisco,55.0,49.5,23.5,37.9,29.1,24.3,16.8,19.8,35.1,34.3,56.6,48.3
Bradley,55.1,47.6,27.5,35.1,28.1,28.2,18.1,18.3,37.0,33.0,54.9,46.5
Eastern Kentucky,50.6,49.8,32.0,29.5,33.1,31.0,16.1,13.9,36.1,38.7,48.8,45.6
...,...,...,...,...,...,...,...,...,...,...,...,...
Villanova,50.6,48.3,26.8,26.0,24.9,24.3,14.7,16.2,33.8,32.8,50.5,47.6
South Carolina,50.9,48.4,31.8,31.6,32.8,27.9,15.5,14.9,33.9,33.9,50.9,47.3
William & Mary,48.3,52.2,31.9,34.9,27.4,29.1,16.3,14.4,32.1,34.5,48.6,52.5
Stonehill,46.7,52.7,22.6,29.4,22.5,31.0,19.5,16.6,30.1,35.9,47.9,51.7
Green Bay,52.4,49.4,29.4,34.2,27.3,28.4,18.6,14.0,34.0,30.2,53.7,51.6

In [12]:


def get_fffinal():
    df = pd.read_csv(urlopen(FFFINAL))
    df = df.reset_index()

    df.columns = ["TEAM","EFG_O","Rk","EFG_D","Rk","FTR","Rk","FTRD","Rk","ORB","Rk","DRB",
                "Rk","TOR","Rk","TORD","Rk","3P_O","rk","3P_D","rk","2P_O","rk","2P_D","rk",
                "ft%","rk","ft%D","rk","3P rate","rk","3P rate D","rk","arate","rk","arateD","rk",
                "1", "2", "3" , "4"]
    
    cols_to_keep = ["TEAM","EFG_O","EFG_D","FTR","FTRD","ORB","DRB","TOR","TORD","3P_O","3P_D","2P_O","2P_D"]

    return df[cols_to_keep].set_index("TEAM")

In [13]:
test = get_fffinal()

In [14]:
test

,EFG_O,EFG_D,FTR,FTRD,ORB,DRB,TOR,TORD,3P_O,3P_D,2P_O,2P_D
TEAM,,,,,,,,,,,,
North Dakota,50.2,52.4,32.2,29.6,30.7,26.1,15.0,15.3,32.3,35.2,51.5,52.2
Appalachian St.,52.7,45.4,31.6,20.7,29.4,27.8,15.2,14.5,33.2,32.1,53.9,44.0
San Francisco,55.0,49.5,23.5,37.9,29.1,24.3,16.8,19.8,35.1,34.3,56.6,48.3
Bradley,55.1,47.6,27.5,35.1,28.1,28.2,18.1,18.3,37.0,33.0,54.9,46.5
Eastern Kentucky,50.6,49.8,32.0,29.5,33.1,31.0,16.1,13.9,36.1,38.7,48.8,45.6
...,...,...,...,...,...,...,...,...,...,...,...,...
Villanova,50.6,48.3,26.8,26.0,24.9,24.3,14.7,16.2,33.8,32.8,50.5,47.6
South Carolina,50.9,48.4,31.8,31.6,32.8,27.9,15.5,14.9,33.9,33.9,50.9,47.3
William & Mary,48.3,52.2,31.9,34.9,27.4,29.1,16.3,14.4,32.1,34.5,48.6,52.5
Stonehill,46.7,52.7,22.6,29.4,22.5,31.0,19.5,16.6,30.1,35.9,47.9,51.7
Green Bay,52.4,49.4,29.4,34.2,27.3,28.4,18.6,14.0,34.0,30.2,53.7,51.6